---
    - name: install nginx latest version
      apt:
        name: nginx
        state: latest
    - name: delete default site
      file:
        path: /etc/nginx/sites-available/default
        state: absent
      become: yes
    - name: start nginx
      service:
        name: nginx
        state: started
      become: yes
